name: habbit_pub
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  dartz: 
  get_it:
  equatable:

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito:
flutter:

  uses-material-design: true

